---
abstract: ''
author:
  - 'cho45 <cho45@lowreal.net>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SQL-NamedPlaceholder
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Exporter::Lite: 0
  Scalar::Util: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/cho45/SQL-NamedPlaceholder
version: 0.02
